#!/bin/bash

brew install eza
brew install fzf
brew install ripgrep
brew install tree

brew install powerlevel10k
brew install zsh-autosuggestions
brew install zsh-syntax-highlighting
brew install --cask font-fira-code-nerd-font

brew install jesseduffield/lazygit/lazygit

brew install docker

