return {
	"nvim-treesitter/nvim-treesitter",
	branch = "main",
	version = false,
	build = ":TSUpdate",
	event = { "BufReadPre", "BufNewFile" },
	config = function()
		local treesitter = require("nvim-treesitter")
		treesitter.install({
			"astro",
			"bash",
			"elixir",
			"html",
			"odin",
			"javascript",
			"jsdoc",
			"json",
			"lua",
			"luadoc",
			"luap",
			"markdown",
			"markdown_inline",
			"python",
			"query",
			"regex",
			"solidity",
			"styled",
			"tsx",
			"typescript",
			"terraform",
			"vim",
			"vimdoc",
			"yaml",
			"go",
		})
	end,
}
