return {
	-- {
	-- 	"CopilotC-Nvim/CopilotChat.nvim",
	-- 	dependencies = {
	-- 		{ "github/copilot.vim" },
	-- 		{ "nvim-lua/plenary.nvim", branch = "master" },
	-- 	},
	-- 	build = "make tiktoken", -- Only on MacOS or Linux
	-- 	opts = {},
	-- 	keys = {
	-- 		-- Toggle CopilotChat window
	-- 		{
	-- 			"<leader>at",
	-- 			function()
	-- 				require("CopilotChat").toggle()
	-- 			end,
	-- 			desc = "CopilotChat - Toggle chat",
	-- 		},
	-- 		-- Prompt actions for normal mode (buffers context)
	-- 		{
	-- 			"<leader>ap",
	-- 			function()
	-- 				require("CopilotChat").select_prompt({ context = { "buffers" } })
	-- 			end,
	-- 			desc = "CopilotChat - Prompt actions",
	-- 		},
	-- 		-- Prompt actions for visual mode (default context)
	-- 		{
	-- 			"<leader>ap",
	-- 			function()
	-- 				require("CopilotChat").select_prompt()
	-- 			end,
	-- 			mode = "x",
	-- 			desc = "CopilotChat - Prompt actions",
	-- 		},
	-- 		-- Explain code
	-- 		{ "<leader>ae", "<cmd>CopilotChatExplain<cr>", desc = "CopilotChat - Explain code" },
	-- 		-- Review code
	-- 		{ "<leader>ar", "<cmd>CopilotChatReview<cr>", desc = "CopilotChat - Review code" },
	-- 		-- Quick chat input
	-- 		{
	-- 			"<leader>ai",
	-- 			function()
	-- 				local copilot_chat = require("CopilotChat")
	-- 				local select = require("CopilotChat.select")
	-- 				local input = vim.fn.input("Ask Copilot: ")
	-- 				if input ~= "" then
	-- 					copilot_chat.ask(input, { selection = select.buffer })
	-- 				end
	-- 			end,
	-- 			desc = "CopilotChat - Quick chat",
	-- 		},
	-- 	},
	-- },
}
